### ISSUE TITLE
dataset of isomers

### ISSUE THREAD

**Issue by Colin-Jay** [Anan-Wu-XMU/SVM-M#4]
Dear Prof. Anan,
Thank you teacher for your wonderful work! Could you please provide the data on 2-7 among the isomers?
Thanks

**Comment by Anan-Wu-XMU** [comment]
You may come to 曾呈奎楼B406 and discuss this in details.

**Comment by Colin-Jay** [comment]
> You may come to 曾呈奎楼B406 and discuss this in details.

谢谢老师！数据集的问题我已经解决，如果您有时间我最近去找您沟通学习！
